### PR TITLE
test/stats: make tests involving floating point calculations more lax

### PR DESCRIPTION
**Pull request by ukleinek**
On i387 floating point calculations can be quite surprising. The motivation for this change came from the observation that compiling and testing rauc-1.8 on the i386 Debian build machine had a failure on

	g_assert_cmpfloat(r_stats_get_avg(stats), ==, 62.54615384615385);

. In that case r_stats_get_avg(stats) (when stored in a double typed variable) returned

	0x1.f45e85e85e85fp+5

which is 0x1f45e85e85e85f00 / 2**55. However when stored in a long double typed variable it has the value

	0x1.f45e85e85e85e85p+5

This value is 0x1f45e85e85e85e85 / 2**55 and so it has a significand that cannot be stored in the 53 bits that are allocated for double typed variables. 62.54615384615385 is a plain double and so evaluates to 0x1.f45e85e85e85fp+5.

This makes the comparison implemented in g_assert_cmpfloat() (which uses long double precision) fail. To fix that, use
g_assert_cmpfloat_with_epsilon() and also adapt the other tests that involve non-trivial calculations to this approach.

Fixes: https://github.com/rauc/rauc/issues/996
Signed-off-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>

### CODE REVIEW

**Comment by jluebbe** [comment]
This breaks the build for glib versions < 2.58. Do we want to update the minimum version, backport the implementation of g_assert_cmpfloat_with_epsilon or implement the assert a different way?

**Comment by ukleinek** [comment]
> This breaks the build for glib versions < 2.58. Do we want to update the minimum version, backport the implementation of g_assert_cmpfloat_with_epsilon or implement the assert a different way?

Not sure if the question is directed at me, but I don't have a strong opinion. With my Debian hat on: glib 2.58 isn't a problem, that version is even contained in buster (aka Debian 10 aka oldstable).

**Comment by jluebbe** [comment]
glib 2.58 is included since:
- Yocto thud (2.58.0)
- Ubuntu focal (2.64.6), bionic has only 2.56.4 but is LTS until April 2023.

So the question become if we want to drop support for bionic. @ejoerns?

**Comment by ejoerns** [comment]
Could be use a preprocessor switch to use the new comparison when glib is newer and the old one when glib is older?

Then we can support either 'old' platforms (glib < 2.58) or 'special' platforms (as i387). But not both at once.

So the only thing is that I would not like to bump the minimal version just because of a test (and not at least because of an added feature).

On the other hand, I would also not strongly insist on keeping the current glib version as the minimum...

Hasn't there been something we thought about breaking compatibility with ubuntu 18.04 for anyway?

**Comment by ukleinek** [comment]
> glib 2.58 is included since:
> 
>     * Yocto thud (2.58.0)
> 
>     * Ubuntu focal (2.64.6), bionic has only 2.56.4 but is LTS until April 2023.

 *  ptxdist 2019.04.0 (2.60.0)

**Comment by ukleinek** [comment]
> Maybe something like:
> 
> ```
> /* g_assert_cmpfloat_with_epsilon exists in glib >= 2.58 */
> #ifndef g_assert_cmpfloat_with_epsilon
> #define g_assert_cmpfloat_with_epsilon(n1, n2, epsilon) \
>     g_assert_true (abs (n1 - n2) < epsilon)
> #endif
> ```

While the documentation claims this was the equivalent expression this results in a warning:

    test/stats.c:10:24: warning: using integer absolute value function ‘abs’ when argument is of floating-point type ‘double’ [-Wabsolute-value]

There is `fabs(3)` which requires `#include <math.h>` and `-lm` though.

Alternatively:

```
/* g_assert_cmpfloat_with_epsilon exists in glib >= 2.58 */
#ifndef g_assert_cmpfloat_with_epsilon
#define g_assert_cmpfloat_with_epsilon(n1, n2, epsilon) \
    G_STMT_START { \
        double __d = n1 - n2;
        if (__d < 0)
            __d = -__d;
        g_assert_true (__d < epsilon)
    } G_STMT_END
#endif
```

**Comment by ejoerns** [comment]
> 

This, or like the G_APPROX_VALUE from glib

``` c
#define G_APPROX_VALUE(a, b, epsilon) \
  (((a) > (b) ? (a) - (b) : (b) - (a)) < (epsilon))
```

The glib implementation probably has better error output, but maybe it's not worth porting the entire define.

``` c
#define g_assert_cmpfloat_with_epsilon(n1,n2,epsilon) \
    G_STMT_START { \
        double __n1 = (n1), __n2 = (n2), __epsilon = (epsilon); \
        if (G_APPROX_VALUE (__n1,  __n2, __epsilon)) ; else \
            g_assertion_message_cmpnum (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, \
              #n1 " == " #n2 " (+/- " #epsilon ")", __n1, "==", __n2, 'f'); \
    } G_STMT_END
```

**Comment by jluebbe** [comment]
We've already back-ported code from glib in similar situations, so I'd prefer just picking both macros (`G_APPROX_VALUE` and `g_assert_cmpfloat_with_epsilon`) to test/common.h with a `#ifndef` protection.

**Comment by ejoerns** [comment]
@ukleinek could you run the uncrustify script on this to make it match our style flavors? :smirk: 
Then I guess it's ready for being merged, thanks!

**Review by ejoerns — APPROVED** [review]
Thanks!

**Review by jluebbe — APPROVED** [review]

**Pull request merged**
