### PR TITLE
Add missing qt type annotations

### PR DESCRIPTION
**Pull request by richardhozak**
Adds qt type annotations so classes can be generated with `qdbusxml2cpp`.

### CODE REVIEW

**Comment by ejoerns** [comment]
@richardhozak Thank you for contributing! Could you add your [Signged-off-by](https://rauc.readthedocs.io/en/latest/contributing.html#developer-s-certificate-of-origin) line to make the PR ready for being merged? Also please align your commit title with the prefixes used for this file (`de.pengutronix.rauc.Installer.xml: `).

While at it, maybe also move the unrelated whitespace fix to a separate commit. Thanks!

**Comment by ejoerns** [comment]
> I've signed off the commit, should I also remove the whitespace change? Seems unnecessary to create another commit for it.

Thank you for your adaption. I would have said adding another commit to the PR should not be a big deal, but I'd also be fine now with keeping it as-is.

**Comment by jluebbe** [comment]
You're using a GitHub generated email address in the author field and SoB line: https://github.com/rauc/rauc/commit/87c40b6768189e84188584486b1cfad5b1fab62f.patch

Is that intentional?

**Comment by richardhozak** [comment]
Yes, that's intentional, I use it for all my commits.

**Review by jluebbe — APPROVED** [review]

**Pull request merged**
