### PR TITLE
Initializing middle

### PR DESCRIPTION
**Pull request by b4yuan**
Variable `middle` coule be uninitialized at the access of the variable on line 481 in `hash_index.c`; adding a line that initializes middle to 0.

### CODE REVIEW

**Comment by jluebbe** [comment]
> Variable `middle` coule be uninitialized at the access of the variable on line 481 in `hash_index.c`; adding a line that initializes middle to 0.

Line 481 is only executed if found is true, and in that case middle is always initialized.

For consistency, we could set it to 0, though. Could you add your Signed-off-by (see https://github.com/rauc/rauc/pull/1155/checks?check_run_id=14152982601)?

**Review by ejoerns — CHANGES_REQUESTED** [review]
Branch modification by maintainers is disabled in the branch, thus I write my proposal for a proper commit message here:

>    src/hash_index: initialize 'middle' for consistency
>
 >   Note that it was not actually used uninitialized since using it depended on
 >   having 'found' set to TRUE which can only happen in a code path that also
 >   sets 'middle' to some value.

Must not be taken exactly but at least the path prefix (`src/hash_index`) should be included.

**Comment by jluebbe** [comment]
This now includes both versions of the commit message and a merged. https://github.com/rauc/rauc/pull/1155/commits should only include a single patch with the new commit message.

**Comment by b4yuan** [comment]
I'm not given the option of "Allow edits and access to secrets by maintainers" in the sidebar.

**Comment by jluebbe** [comment]
> I'm not given the option of "Allow edits and access to secrets by maintainers" in the sidebar.

Hmm, perhaps this is related to the use of a organisation repository as the source. I'll open a new PR with your commit to get this in.

**Comment by jluebbe** [comment]
If you'd like, you can add a review on https://github.com/rauc/rauc/pull/1171.

**Comment by ejoerns** [comment]
> I'm not given the option of "Allow edits and access to secrets by maintainers" in the sidebar.

You should be able to force-push your own branches, anyway. But I guess #1171 does it, too.

**Pull request closed without merging**
