### PR TITLE
Add dm-crypt section to faq documentation page

### LINKED ISSUE #830: RAUC and plain dm-crypt volumes as rootfs slots
Hi,

I am currently playing around with a system which is running on a plain dm-crypt volume mapped ext4 rootfs.

boot partitions are currently configured as slot type vfat and root partitions are configured as slot type raw.

Is there any best practice on how to handle this use case? I tried to use a dm-crypt volume as rootfs slot but then of course the squashFS compression is not able to compress anything anymore ;)

regards, 
Fabian

### PR DESCRIPTION
**Pull request by fabianbuettner**
Closes #830 
Signed-off-by: Fabian Büttner <fabian.buettner@rub.de>

### CODE REVIEW

**Comment by ejoerns** [comment]
Thanks for the patch!

Please let the Mail used for Signed-off-by match your git commit author mail (see DCO check failure)

**Comment by fabianbuettner** [comment]
Sorry, I forgott to change the author's email address to use the correct email address. This is my first PR :) what's the right way to fix this?

**Comment by ejoerns** [comment]
@fabianbuettner no worries ;) You can just fix you commit and force-push on the branch you created this PR from

**Review by jluebbe — APPROVED** [review]
I've added an example config snippet and made some minor wording changes.

Thanks for your contribution!

**Review by ejoerns — APPROVED** [review]

**Pull request merged**
