### PR TITLE
Heavy Documentation Extension Patch Stack

### PR DESCRIPTION
**Pull request by ejoerns**
As a result of one week full-time documentation work, this patch stack now heavily extends the RAUC documentation and clarifies a lot of design considerations, handlings, expectations and ways to solve scenarios people asked for over the last month. And even more!

### CODE REVIEW

**Comment by rohieb** [comment]
I've pushed some fixes to https://github.com/rohieb/rauc/commit/4cfd7134561135f625728d9825749f9903fc9714.

**Comment by ejoerns** [comment]
:+1:  I've added your patch to the stack

**Comment by jluebbe** [comment]
In doc/index.rst there are two missing images.

**Comment by ejoerns** [comment]
@jluebbe squashed your changes into the patch stack and added the two missing images

**Comment by jluebbe** [comment]
There are still some problems reported by sphinx in travis:
docs/index.rst:105: WARNING: image file not readable: images/rauc_update_cases.png
docs/integration.rst:653: ERROR: Unknown target name: "system configuration file".
docs/integration.rst:653: ERROR: Unknown target name: "chapter".

**Comment by ejoerns** [comment]
You are right, I've fixed it. And to prevent from missing such issues in the future, I also modified the .travis.yml to build the doc with treating warnings as errors.

**Pull request merged**
