### PR TITLE
Issue 357: Improve version mangling

### PR DESCRIPTION
**Pull request by ukleinek**
by making the globs for detecting an old git stricter the check actually works also for rc releases. Together with the second change a release candidate doesn't use a . in the version string which fixes issue 357.

### CODE REVIEW

**Comment by jluebbe** [comment]
It seems that upstream for that script has fixed the issue we see:
https://github.com/coreutils/gnulib/commits/master/build-aux/git-version-gen
Do you think that updating the the most recent one would fix #357 as well?

**Comment by ejoerns** [comment]
@ukleinek Any comments on this from your side?

**Comment by ukleinek** [comment]
I did:

    $ git checkout v1.0-rc1
    ...
    $ git show f63891af3567fd2f6c8e754e46b76fd7ff0a3948:build-aux/git-version-gen > git-version-gen-old
    $ wget https://raw.githubusercontent.com/coreutils/gnulib/9447bd9732613c5419611bcb2b8b304d748b62b6/build-aux/git-version-gen
    ....

Just for the record:

    $ sh git-version-gen-old .tarball-version; echo # this is the broken one
    1.0.1-rc1
    $ sh build-aux/git-version-gen .tarball-version; echo # this is the fixed up with a . instead of -

So yes, an update would also fix #357.
    1.0.rc1

With the new upstream version it seems to do the right thing:

    $ sh git-version-gen .tarball-version; echo
    1.0-rc1

**Comment by ejoerns** [comment]
As #436 was merge, I assume this to be fixed, too

**Pull request closed without merging**
