### PR TITLE
system_variant as g_array

### PR DESCRIPTION
**Pull request by js731ca**
Convert the `system_variant` kept in the context from a single element to an array; so that a bundle can specify a 'broader' compatibility than just the most exact one.

This PR targets the `variant-dtb=true` feature, where rauc now reads in the full list of compatibles (and not just the very first one...) stored in `/sys/firmware/devicetree/base/compatible` [1] and compares the variant set on a slot in the bundle against *each* of the elements in the devices compatibility hierarchy.

A usage scenario/example: 
On a system with secure-boot, where the bootloader has to be signed against one key/cert out of a set of keys/certs, which can be (individually) revoked.
The running bootloader "would know" which keys/certs are still "open" and append them as of-fixup to the devicetree/compatible.
Bundles would have a variant set on *every* slot (e.g. not leaving an unset/default), where the bootloader.variant could reflect the signature as a compatible; which would then ensure that the bundle installation fails if there are no compatible elements in the bundle - ensuring that the device could not get bricked.
```
# example bundle:
[update]
compatible=ACME Coorp
version=4.3.2
description=acme corp embedded device update bundle
build=20240823202207
...
[image.bootloader.acme,dev001-K2]
sha256=f734326e25a2e1f1b516d7013dd1aabe145441fc61ee5e508e6e83f1542b2a8c
size=1597980
filename=barebox-acme-dev001-s.img

# the bootloader would know which keys/certs are revoked, and fixup the compatible accordingly:
$> cat /sys/firmware/devicetree/base/compatible
acme,dev001-revP\0acme,dev001-K1\0acme,dev001-K3\0acme,dev001\0fsl,imx8mm\0

# so in this scenario, the bundle would just refuse to install
# -> not bricking the device
$> rauc install /tmp/acme-bootloader-bundle-dev001-20240823202207.raucb 
installing                                                                                                       
  0% Installing                                                                                                  
  0% Determining slot states                                                                                     
 10% Determining slot states done.                                                                               
 10% Checking bundle                                                                                             
 10% Verifying signature
 20% Verifying signature done.                                                                                   
 20% Checking bundle done.                                                                                       
 20% Checking manifest contents                                                                                  
 30% Checking manifest contents done.
 30% Determining target install group
 40% Determining target install group done.
100% Installing failed.
LastError: Installation error: Failed to find matching variant of image for bootloader
Installing `/tmp/acme-bootloader-bundle-dev001-20240823202207.raucb` failed
```

Note that this implementation is currently only focused on the concept/feature, and would need to be covered by more tests...
But first -> RFC :-)

Also: this "one-dimensionality" could be carried over to the other two: `variant-file` and `variant-name` features - which would make them more useful/powerful

[1] https://www.kernel.org/doc/html/latest/devicetree/usage-model.html#platform-identification

### CODE REVIEW

**Comment by jluebbe** [comment]
> Bundles would have a variant set on _every_ slot (e.g. not leaving an unset/default), where the bootloader.variant could reflect the signature as a compatible; which would then ensure that the bundle installation fails if there are no compatible elements in the bundle - ensuring that the device could not get bricked.

If I understand correctly, you want to use RAUC's variant mechanism to reject installation of the bundle is specific cases. While it could be used for that, it's actually intended to be used to *select* one one several alternative images in the bundle which perform the same function in the system (i.e. bootloaders for different SoCs used with a common kernel and root filesystem).

RAUC's mechanism to allow/reject installation of a bundle is the compatible: either with fixed string or by using the [`install-check` hook](https://rauc.readthedocs.io/en/latest/using.html#install-hooks). When using a hook, the script can introspect the running system (e.g. which fuses are burned) and then decide based on logic in the script.

Bundle [meta-data](https://rauc.readthedocs.io/en/latest/reference.html#meta-label-sections) could be exposed to this hook as well. You'd have something like
```ini
[meta.hab]
signature-key=3
```
and then check in the `install-check` hook whether that key is still valid.

It may be useful to define a new hook, which doesn't replace the built-in compatible check. Instead it would only run if the build-in one was successful to implement additional restrictions.

**Comment by js731ca** [comment]
Thanks for the input!
I'll take a look at the hook implementation

the "but" here is that their error response isn't "as nice" as an integrated feature would be - looking back at the stop-gap solution for the min-version check, which is/was also a hook: rauc would start installation and then in-medias-res just fail, with no good error response (unless one knew to look in the rauc.service log, and for what...) 
here the response is direct and pretty clear: incompatible, stop!

for the usecase described: yes, that's a way to (ab)use this feature, IMO it could be generally usefull though: think about a set of boards that define a compatible hierarchy:
acme,device-rev01; acme,device; fsl,imx8mm
acme,device-rev42; acme,device; fsl,imx8mm
acme,fooo-rev44; acme,foo; fsl,imx8mm
here a bundle slot compatible check could say "ok, for acme,device, take this bootloader"; or another one that runs on all "fsl,imx8mm" (without being the no-variant-set default)

**Comment by ejoerns** [comment]
> Thanks for the input! I'll take a look at the hook implementation
> 
> the "but" here is that their error response isn't "as nice" as an integrated feature would be - looking back at the stop-gap solution for the min-version check, which is/was also a hook: rauc would start installation and then in-medias-res just fail, with no good error response (unless one knew to look in the rauc.service log, and for what...) here the response is direct and pretty clear: incompatible, stop!

This is not fully correct I guess. From https://rauc.readthedocs.io/en/latest/using.html#install-hooks:

> If available, RAUC will use the last line printed to standard error by the hook executable as the rejection reason message and provide it to the user:

And the final error returned over D-Bus should include this error as well.

Thus the only thing that might be missing is having distinguishable error codes as discussed in https://github.com/rauc/rauc/issues/690. But that would be the same with your approach.

> for the usecase described: yes, that's a way to (ab)use this feature, IMO it could be generally usefull though: think about a set of boards that define a compatible hierarchy: acme,device-rev01; acme,device; fsl,imx8mm acme,device-rev42; acme,device; fsl,imx8mm acme,fooo-rev44; acme,foo; fsl,imx8mm here a bundle slot compatible check could say "ok, for acme,device, take this bootloader"; or another one that runs on all "fsl,imx8mm" (without being the no-variant-set default)

We had a similar expectation in https://github.com/rauc/rauc/issues/807 and I remember vaguely having discussed something similar already. The thing is that adding this would increase complexity in handling variants, etc. Thus maybe we should find out first if there are actual use cases that are hard to solve with the existing mechanism..?

**Comment by jluebbe** [comment]
@js731ca You can use https://github.com/rauc/rauc/pull/1506 to have access to the manifest meta-data in the install-check hook.

**Comment by js731ca** [comment]
> We had a similar expectation in #807 and I remember vaguely having discussed something similar already.

rauc only looks at the very first compatible = the most specific one

>  The thing is that adding this would increase complexity in handling variants, etc. Thus maybe we should find out first if there are actual use cases that are hard to solve with the existing mechanism..?

agreed, "complexity is the enemy" :-D
enabling rauc to look through each element in the  devicetree/base/compatible would have been usefull for #807... since that is what this user was asking for: "how to have a variant targeting not-the-first compatible"

**Comment by js731ca** [comment]
@bith3ad has the bigger picture of "our" usecases, and we're going to handle the problem via the infrastructure and signing-providers = outside of rauc, but inside meta-rauc/yocto

-> so the immediate need for this PR dissolved, should we close it or continue on since it "might still be useful"? (-:

**Comment by jluebbe** [comment]
> agreed, "complexity is the enemy" :-D
> enabling rauc to look through each element in the devicetree/base/compatible would have been useful for #807... since that is what this user was asking for: "how to have a variant targeting not-the-first compatible"

Yes, but "a variant targeting not-the-first compatible" may not be the best solution for their use-case when considering RAUC's design and long-term maintenance.

> @bith3ad has the bigger picture of "our" usecases, and we're going to handle the problem via the infrastructure and signing-providers = outside of rauc, but inside meta-rauc/yocto

Please check if you can handle it with an `install-check` hook and meta-data.

> -> so the immediate need for this PR dissolved, should we close it or continue on since it "might still be useful"? (-:

I'll close this for now. Some things that would need to be solved before merging something similar:

- [ ] analyze how multiple variants should interact with multiple compatibles (sooner or later someone would ask why multiple variants are supported but not multiple compatibles)
- [ ] write documentation, with guidance on how to use multiple variants, especially with regards to forwards/backwards compatibility
- [ ] decide how multiple variants interact with bundles with/without default images (i.e. is there an implicit "default" variant at the end of the list?)
- [ ] decide how to expose the variant list via D-Bus and via environment vars (which currently use only a single string)
- [ ] review the design for corner cases and possibly surprising behaviour

**Pull request closed without merging**
