### PR TITLE
Fixes for context setup and error handling

### PR DESCRIPTION
**Pull request by ejoerns**
* always back fallback to `/etc/rauc/system.conf` when being available (but error if its broken)
* graceful context error printout for all rauc commands

### CODE REVIEW

**Comment by tretter** [comment]
I tested `rauc info` without the `--keyring` argument, and it works again as before.

**Comment by ejoerns** [comment]
As suggested by @jluebbe, I've 'slightly' reduced code code duplication by simply moving the `r_context_configure()` call before the call of the individual command handler.

**Comment by ejoerns** [comment]
Did sound like a good plan, but call to `r_context_configure()` must actually happen *after* call to `r_context_conf()->configpath`. But the latter is command-specific.

**Comment by ejoerns** [comment]
Deprecated by #840.

**Pull request closed without merging**
