### PR TITLE
src/update_handler: copy_raw_image() close out_fd in case of failure

### LINKED ISSUE #761: After installation error rauc keeps target partition open
We encountered a installation error with the following log:
```
Aug 11 10:42:40 rauc[408]: input bundle: /data/swupdate/FromGAT/SW61.upd
Aug 11 10:42:40 rauc[408]: Active slot bootname: A
Aug 11 10:42:40 rauc[408]: installing /data/swupdate/FromGAT/SW61.upd: started
Aug 11 10:42:40 rauc[408]: Reading bundle: /data/swupdate/FromGAT/SW61.upd
Aug 11 10:42:40 rauc[408]: installing /data/swupdate/FromGAT/SW61.upd: Checking and mounting bundle...
Aug 11 10:42:40 rauc[408]: Verifying bundle signature... 
Aug 11 10:42:40 rauc[408]: Verified inline signature by '<redacted>'
Aug 11 10:42:40 rauc[408]: Mounting bundle '/data/swupdate/FromGAT/SW61.upd' to '/run/rauc/bundle'
Aug 11 10:42:40 rauc[408]: Configured loop device '/dev/loop0' for 153702400 bytes
Aug 11 10:42:40 kernel: device-mapper: verity: sha256 using implementation "sha256-ce"
Aug 11 10:42:40 rauc[408]: Configured dm-verity device '/dev/dm-0'
Aug 11 10:42:40 rauc[408]: Marking target slot rootfs.1 as non-bootable...
Aug 11 10:42:40 rauc[408]: installing /data/swupdate/FromGAT/SW61.upd: Updating slots...
Aug 11 10:42:40 rauc[408]: Checking image type for slot type: ext4
Aug 11 10:42:40 rauc[408]: installing /data/swupdate/FromGAT/SW61.upd: Checking slot rootfs.1
Aug 11 10:42:40 rauc[408]: Slot needs to be updated with /run/rauc/bundle/rootfs.ext4
Aug 11 10:42:40 rauc[408]: Updating /dev/mmcblk2p2 with /run/rauc/bundle/rootfs.ext4
Aug 11 10:42:40 rauc[408]: installing /data/swupdate/FromGAT/SW61.upd: Updating slot rootfs.1
Aug 11 10:42:40 rauc[408]: opening slot device /dev/mmcblk2p2
Aug 11 10:42:40 rauc[408]: writing data to device /dev/mmcblk2p2
Aug 11 10:42:49 kernel: SQUASHFS error: squashfs_read_data failed to read block 0x3f46a00
Aug 11 10:42:49 kernel: SQUASHFS error: Unable to read data cache entry [3f46a00]
Aug 11 10:42:49 kernel: SQUASHFS error: Unable to read page, block 3f46a00, size e2e8
Aug 11 10:42:49 kernel: SQUASHFS error: Unable to read data cache entry [3f46a00]
Aug 11 10:42:49 kernel: SQUASHFS error: Unable to read page, block 3f46a00, size e2e8
Aug 11 10:42:49 kernel: SQUASHFS error: Unable to read data cache entry [3f46a00]
Aug 11 10:42:49 kernel: SQUASHFS error: Unable to read page, block 3f46a00, size e2e8
Aug 11 10:42:49 kernel: SQUASHFS error: Unable to read data cache entry [3f46a00]
Aug 11 10:42:49 kernel: SQUASHFS error: Unable to read page, block 3f46a00, size e2e8
Aug 11 10:42:49 kernel: SQUASHFS error: Unable to read data cache entry [3f46a00]
Aug 11 10:42:49 kernel: SQUASHFS error: Unable to read page, block 3f46a00, size e2e8
Aug 11 10:42:49 rauc[408]: Installation error: Failed updating slot rootfs.1: Failed splicing data: Error reading from file: Input/output error
Aug 11 10:42:49 rauc[408]: installing /data/swupdate/FromGAT/SW61.upd: Installation error: Failed updating slot rootfs.1: Failed splicing data: Error reading from file: Input/output error
Aug 11 10:42:49 rauc[408]: installing /data/swupdate/FromGAT/SW61.upd: finished
Aug 11 10:42:49 rauc[408]: installing `/data/swupdate/FromGAT/SW61.upd` failed: 1
```

When we tried to repeat the update rauc failed with
```
Installation error: Failed updating slot rootfs.1: Opening output device /dev/mmcblk2p2 failed: Device or resource busy
```
And checking `lsof` revealed, that rauc still had `/dev/mmcblk2p2` opened:
```
# lsof | grep mmc
408     /usr/bin/rauc   /dev/mmcblk2p2
```

### PR DESCRIPTION
**Pull request by chhitz**
As automatically closing of the fd is explicitly disabled, the fd needs to
be closed manually in case of any errors.

Signed-off-by: Christian Hitz <christian.hitz@bbv.ch>

Fixes #761

### CODE REVIEW

**Review by Jarsop — COMMENTED** [review]
Well, maybe a better way for harmony with other functions and to avoid code repetition is to use goto syntax. As we have a `close` at the end you can put the `out` label just above (you have examples in the same source file) @jluebbe what do you think about of this?

**Comment by a3f** [comment]
Alternatively, https://github.com/rauc/rauc/blob/f16db69fc8c9cc2e2cbe4c5074811fe5e56415bc/src/checksum.c#L22 uses Glib `g_auto` to let GCC worry about closing the FD.

If we do likewise here, it means we will lose the `Closing output device failed` message. I guess that's fine. I find a `close(1)` error unlikely if `fsync(1)` before succeeded.

**Comment by Jarsop** [comment]
With goto way you need check `res` value before setting the error and in case of it is `FALSE` use `propagate_error` instead

**Review by ejoerns — DISMISSED** [review]
Following @a3f's argumentation, I would also see this as a proper solution.

Good catch!

**Comment by jluebbe** [comment]
I'm not convinced that this is correct. The file descriptor belongs to the ``GUnixOutputStream``, which is freed via g_auto in the calling functions.
I'd argue that adding the ``g_unix_output_stream_set_close_fd(outstream, FALSE)`` in 549d79b5d6ea64d1524a406b7914a799d0775ae8 was not fully correct, as we want to close the FD in any case. We can call fsync on it without closing it in ``copy_raw_image()``. Checking the error from close can also be done from the calling function (in the non-error case) by calling g_output_stream_close().

**Comment by chhitz** [comment]
> We can call fsync on it without closing it in `copy_raw_image()`. Checking the error from close can also be done from the calling function (in the non-error case) by calling g_output_stream_close().

@jluebbe  is this what you had in mind: https://github.com/chhitz/rauc/commit/538b9937994d946734b408bf2a6c2642156113a9

**Comment by ejoerns** [comment]
As this did not receive any update since my last comment, I've now tried to condense all the previous commits and mentions into a single commit (and message):

https://github.com/ejoerns/rauc/commit/ff6b9a85d4ef3d084d6bd1da4c49d1f0db97e1c3

**Comment by jluebbe** [comment]
I've now combined https://github.com/chhitz/rauc/commit/538b9937994d946734b408bf2a6c2642156113a9 with the commit message and fix from https://github.com/ejoerns/rauc/commit/ff6b9a85d4ef3d084d6bd1da4c49d1f0db97e1c3. Also I've moved some `g_output_stream_close()` out from the if/else when handling casync files.

**Comment by jluebbe** [comment]
Rebased to current master.

**Review by jluebbe — APPROVED** [review]

**Review by ejoerns — APPROVED** [review]

**Pull request merged**
