### PR TITLE
Fix "mark-{bad,good}  other" only works for A/B setups

### PR DESCRIPTION
**Pull request by N3xp7im3**
Marking multiple slots with "rauc status mark-{bad,good} other" only works for two slots.
As this behavior might not be intentional, this PR implements support for setups with more than two slots. So now when using the command above more than two slots can be marked.

In order to write test cases I rebased my patches onto the following PR [1].
This avoids reinventing the wheel by using the ABC config and fixtures used in their PR.

[1] https://github.com/rauc/rauc/pull/1525

### CODE REVIEW

**Comment by ejoerns** [comment]
FTR: I have an updated PR for #1525 in progress which rebases onto current master and incorporates the changes made in #1567 and #1572. This should resove some of the conflicts.

**Comment by ejoerns** [comment]
I've split up my test adaptions so that it should be sufficient to cherry-pick 38cb2e4b4aed8ad1a5c5f1af0884938f7a2f8eac here.

**Comment by N3xp7im3** [comment]
Rebased my changes onto newest PR version of [#1525](https://github.com/rauc/rauc/pull/1525)
Furthermore, I deleted my abc_mark fixture and now use your system_abc fixture instead

**Comment by N3xp7im3** [comment]
Opened new PR which already includes an improved version of this PR
See #1584

**Pull request closed without merging**
