### PR TITLE
docs: advanced: clarify how boot-mbr-switch works

### PR DESCRIPTION
**Pull request by ejoerns**
The former description had formulations like "switching between two partitions" which can be quite misleading as we do not actually switch between two partitions but switch a partition between two regions.

Signed-off-by: Enrico Joerns <ejo@pengutronix.de>

### CODE REVIEW

**Comment by jluebbe** [comment]
In the code and existing documentation, the 'region' covers both parts. In the GPT case we use 'lower and upper halves of a region'.

**Comment by ejoerns** [comment]
@jluebbe yes, this should be consistent. I've adapted the text accordingly.

**Comment by ejoerns** [comment]
I've reworked the whole chapter now to fix the remaining inconsistencies. And tried to be more verbose for the example.

**Comment by jluebbe** [comment]
After realizing that upper/lower region is confusing as well, I've now updated it to use first/second half. Also, I've adjusted the boot-gpt-switch section to match and aligned the partitions in the example layout.

**Review by jluebbe — DISMISSED** [review]

**Review by jluebbe — APPROVED** [review]

**Pull request merged**
