### PR TITLE
docs: integration: document need for 'unsquashfs' tool for 'rauc info'

### PR DESCRIPTION
**Pull request by ejoerns**
Suggested-by: Michael Heimpold michael.heimpold@i2se.com
Signed-off-by: Enrico Jorns <ejo@pengutronix.de>

Fixes: #262

### CODE REVIEW

**Comment by BastianStender** [comment]
Looks good, but shouldn't this get added to the `README.rst` (prerequisites section) as well?

**Comment by ejoerns** [comment]
Mh, it is neither a build dependency nor a real target dependency.

We don't list required target tools there either, thus I would say it is ok to leave this out for the README.rst. Maybe one should add a generic note that depending on the underlying storage and file system types used further target tools can be required?

**Comment by BastianStender** [comment]
I see. What about a link in the `README.rst` pointing to https://rauc.readthedocs.io/en/latest/integration.html#required-target-tools ?

**Comment by BastianStender** [comment]
By the way, `git grep -C10 g_subprocess` reveals more external tools. At least "fakeroot" is not documented anywhere or am I missing something?

**Comment by ejoerns** [comment]
@BastianStender is that more like what you would have expected? ;)

**Comment by BastianStender** [comment]
Yes, very nice :+1:

**Pull request merged**
