### PR TITLE
Fixes typo in documentation

### PR DESCRIPTION
**Pull request by BigPapa314**
Fixes meta-rauc-communit -> meta-rauc-community

### CODE REVIEW

**Review by ejoerns — APPROVED** [review]
Thank you for the fix!

**Comment by ejoerns** [comment]
Note that you can force-push on existing branches to update PRs.

**Comment by ejoerns** [comment]
(I have slightly adapted the title of your commit to match the prefix used in other commits)

**Comment by BigPapa314** [comment]
> (I have slightly adapted the title of your commit to match the prefix used in other commits)

Thanks for giving me a hand.

**Pull request merged**
