### PR TITLE
bundle: allow installing bundle from ZFS partitions

### PR DESCRIPTION
**Pull request by zonque**
Add `ZFS_SUPER_MAGIC` as defines in openzfs.

### CODE REVIEW

**Review by jluebbe — CHANGES_REQUESTED** [review]
https://github.com/openzfs/zfs/blob/master/include/sys/fs/zfs.h#L1198 calls it LINUX_ZFS_SUPER_MAGIC. Please add it to the list in https://github.com/rauc/rauc/blob/master/src/bundle.c#L21-L81 with a comment where it was found.

**Comment by zonque** [comment]
> https://github.com/openzfs/zfs/blob/master/include/sys/fs/zfs.h#L1198 calls it LINUX_ZFS_SUPER_MAGIC. Please add it to the list in https://github.com/rauc/rauc/blob/master/src/bundle.c#L21-L81 with a comment where it was found.

Ah, I missed that list. Thanks!

Also, ZFS apparently cannot be checked with the rdev check in bundle.c so we have to set `mount_checked` to TRUE immediately. Will update.

**Comment by zonque** [comment]
Updated. PTAL.

**Review by jluebbe — APPROVED** [review]

**Comment by jluebbe** [comment]
This should also help with #688.

@zonque You're actually installing from ZFS on embedded devices? Have you tried the verity bundle format?

**Comment by zonque** [comment]
> @zonque You're actually installing from ZFS on embedded devices?

Yes, we're using it both on x86 and raspberrypis.

> Have you tried the verity bundle format?

No, how would that help?

**Comment by jluebbe** [comment]
> > Have you tried the verity bundle format?
> 
> No, how would that help?

With plain bundles, RAUC uses these checks to protect against the TOCTOU vulnerability:
https://rauc.readthedocs.io/en/latest/advanced.html#protection-against-concurrent-bundle-modification

If it detects a verity bundle, these checks are not necessary and skipped.

**Pull request merged**
