### PR TITLE
Added note in docs to restart the service after changing system.conf

### PR DESCRIPTION
**Pull request by SijmenHuizenga**
Just a little note in the docs that would have helped me a bit. Hopefully it will be useful to someone out there :smile:

### CODE REVIEW

**Comment by ejoerns** [comment]
@SijmenHuizenga There is actually such a hint already, but only in the reference section: https://rauc.readthedocs.io/en/latest/reference.html#system-configuration-file
But I do not see anything that speaks against picking this up in the integration section again.

Before I retrigger the CI build that probably lost an acknowledge, maybe you want to fix the commit title prefix (`Docs:`) to be lowercase (and more consistent with the other commits)?

**Comment by ejoerns** [comment]
FTR: The build passed now, seems to have been a browser cache issue on my side

**Comment by SijmenHuizenga** [comment]
Let me know if there is anything else I can do!

**Review by ejoerns — APPROVED** [review]
Looks fine for me.

**Pull request merged**
